---
- name: Happy Birthday Playbook
  hosts: node1
  tasks:
  - name: Wait for ten seconds
    debug:
      msg: "{{ 10 - item }} seconds remaining ..."
    loop: "{{ range(10) | list }}"
    loop_control: 
      pause: 1

  - name: Display Happy Birthday
    debug:
      msg: "Happy Birthday!"
